### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by XandrMaster** [googlecodelabs/android-navigation#72] opened 2019-05-23 15:08 UTC
Did you test your code. Shame on you !!! It Doesn't work if you click on buttons !!!!!!

**Comment by jakobwest** [comment] 2019-06-05 15:11
Until step 9 everything works. When attempting to follow along with step 9, the first issue I ran across is that in the onSupportNavigateUp function, the navigateUp method says "too many arguments" were specified for it. Furthermore, if I run the app at this point, the navigation menu doesn't open when clicking on the menu icon. Any ideas?

Edit: Also clicking the Settings option in the overflow menu doesn't work.

**Comment by QuintenOne** [comment] 2019-06-23 18:53
IIRC, I needed to import another package that has a navigateUp(...) with one argument. If you're in Android Studio, press Alt+Enter to view a menu with the option to import the correct package.

**Comment by linxu-link** [comment] 2019-07-05 02:28
You should follow the instructions

**Comment by ceruleanotter** [comment] 2019-11-08 22:58
I'm closing this issue because I cannot reproduce it in this codelab.

@jakobwest for your issue with the Settings option, in step 9.2 you might have missed removing:

`return super.onOptionsItemSelected(item)`

It's easy to miss if you are moving fast. The other issues are likely incorrect imports - pressing Alt + Enter should resolve. Please re-open this issue with the step number and/or location in the code where you encountered this issue if not

**Closed as completed by ceruleanotter** 2019-11-08 22:58 UTC
