### ISSUE TITLE
Loopin on change orientation

### ISSUE THREAD

**Issue by tiagocasemiro** [googlecodelabs/android-navigation#45] opened 2019-01-15 18:34 UTC
When changing orientation with open fragment. The application loops. The same fragment is started and restarted eternally.

**Comment by ceruleanotter** [comment] 2019-02-23 06:43
Thanks for reporting this and the feedback!

I'm closing this issue because I cannot reproduce it in this codelab. If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.

If you think that this is a problem of the Navigation Component library, please open a bug on the Navigation public issue tracker: https://issuetracker.google.com/issues/new?component=409828&template=1093757

**Closed as completed by ceruleanotter** 2019-02-23 06:43 UTC
