### ISSUE TITLE
There is no navigateUp() fun with AppBarConfiguration param.

### ISSUE THREAD

**Issue by andrewsdv** [googlecodelabs/android-navigation#47] opened 2019-01-17 17:22 UTC
https://github.com/googlecodelabs/android-navigation/blob/master/app/src/main/java/com/example/android/codelabs/navigation/MainActivity.kt#L134

There is no navigateUp() fun with AppBarConfiguration param:
https://developer.android.com/reference/androidx/navigation/NavController.html#navigateUp()

**Comment by sarbogast** [comment] 2019-04-03 04:42
Have a look at the alternative working code proposed in https://github.com/googlecodelabs/android-navigation/issues/66

It works. Apparently this API changed a bit and instead of calling navigateUp() on the NavController, you should call it directly from NavigationUI, where this version accepts a AppBarConfiguration

**Comment by ceruleanotter** [comment] 2019-04-17 23:21
Thanks for reporting this and the feedback!

So the function in question is a Kotlin extension function that is part of NavigationUI; it's documented [here](https://developer.android.com/reference/kotlin/androidx/navigation/ui/package-summary#(androidx.navigation.NavController).navigateUp(androidx.navigation.ui.AppBarConfiguration))

I could not duplicate this issue in the codelab - the extension function is working for me. Perhaps it is an issue with the imports once you uncomment the code? Is `import androidx.navigation.ui.navigateUp` included?

**Comment by ceruleanotter** [comment] 2019-04-30 16:07
I'm closing this issue because I cannot reproduce it in this codelab.

If you still think this is an issue with the codelab, please re-open this issue with additional information (such as whether `import androidx.navigation.ui.navigateUp` was imported)

**Closed as completed by ceruleanotter** 2019-04-30 16:07 UTC
