### ISSUE TITLE
Navigation-Design Preview not updating

### ISSUE THREAD

**Issue by abhishek1508** [googlecodelabs/android-navigation#3] opened 2018-05-09 22:22 UTC
If I try to add a new fragment/actions(for ex.) in the text tab rather than adding it from the design tab; once I add it to the action tab, the changes are not reflected on the design tab. Moreover there is no refresh option that I could see to refresh the design tab. 

It would be great, if the design tab could refresh real time based on the metadata added in the text tab.

**Comment by ceruleanotter** [comment] 2018-10-13 00:02
Hey Abishek - this is (or I think was) an issue with the Navigation Editor that should be reported through the public [Navigation issue tracker](https://issuetracker.google.com/issues?q=componentid:409828%2B%20status:open). I Took a look to see if I could reproduce this behavior but couldn't reproduce on Android Studio 3.2 stable, so closing this issue here. 

If you are still experiencing this on the newest version of Android Studio and using the newest version of the navigation component, please do report it [here](https://issuetracker.google.com/issues/new?component=409828&template=1093757).

**Closed as completed by ceruleanotter** 2018-10-13 00:02 UTC
